import { makeStyles } from "@mui/styles";
const useStyles = makeStyles({
  bookName: {
    color: "#03314B",
    fontFamily: "Cera Pro",
    fontStyle: "normal",
    fontWeight: "600",
    fontSize: "18px",
    lineHeight: "23px",
    top: "23px",
  },
  card: {
    background: "#FFFFFF",
    border: "1px solid #E1ECFC",
    boxSizing: "border-box",
    borderRadius: "8px",
    width: "284px",
    height: "466px",
  },
  author: {
    fontFamily: "Cera Pro",
    fontStyle: "normal",
    fontWeight: "normal",
    fontSize: "16px",
    lineHeight: "20px",
    paddingTop: "16px",
    color: "#6D787E",
    height: "20px",
  },
  read: {
    fontFamily: "Cera Pro",
    fontStyle: "normal",
    fontWeight: "normal",
    fontSize: "14px",
    lineHeight: "18px",
    color: "#6D787E",
    paddingTop: "17px",
    paddingLeft: "5.67px",
  },
  reads: {
    fontFamily: "Cera Pro",
    fontStyle: "normal",
    fontWeight: "normal",
    fontSize: "14px",
    lineHeight: "18px",
    textAlign: "right",
    color: "#6D787E",
    height: "18px",
    width: "64px",
    left: "24px",
    top: "1px",
    borderRadius: "nullpx",
    paddingLeft: "1px",
  },
  time: {
    height: "13.67px",
    width: "16.67px",
    left: "1.67px",
    borderRadius: "0px",
    paddingTop: "17.67px",
    paddingRight: "5.67",
  },
  progress: {
    background: "#F1F6F4",
    top: "15px",
    border: "1px solid #E1ECFC",
    boxSizing: "border-box",
    borderRadius: "0px 0px 8px 8px",
    paddingTop: "5px",
    height: "15px",
    width: "283px",
    left: "0px",
    "& .MuiLinearProgress-colorPrimary": {
      backgroundColor: "#E1ECFC",
    },
    "& .MuiLinearProgress-barColorPrimary": {
      backgroundColor: "#E1ECFC",
    },
  },
  person: {
    height: "13.5px",
    width: "13.33px",
    left: "3.33px",
    top: "3px",
    borderRadius: "0px",
    paddingLeft: "47.33px",
  },

  content: {
    padding: 12,
  },
  button: {
    height: "20px",
    left: "11.5px",
    top: "14px",
    fontFamily: "Cera Pro",
    fontStyle: "normal",
    fontWeight: "500",
    fontSize: "16px",
    lineHeight: "20px",
    color: "#0365F2",
    textTransform: "initial",
    marginLeft: "110px",
  },
  addButton: {
    height: "20px",
    color: "#0365F2",
  },
});
export default useStyles;
